### ISSUE TITLE
ZeroMorph: Implement `phi` function

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#21]
Definition 2.1.1 from ZeroMorph [paper](https://eprint.iacr.org/2023/917.pdf) describes function phi, which receives as input 2 elements: 
* a monomial `a`
* an integer `n`
The output is a univariate polynomial (coefficient representation) in the form `a + aˆ2 + ... + aˆ(2ˆn - 1)`.
In particular, for monomial `X` and `n=2`, we have that `phi(X, 2) = 1 + X + Xˆ2 + Xˆ3`.

**Comment by huitseeker** [comment]
This seems to be simply `std::iter::successors(Some(Fr::ONE), |acc, _| acc * a).take(n).sum()`, and is implemented similarly in many places in https://github.com/lurk-lab/arecibo/tree/zeromorph

You can also do this with `iter::scan`.
The reason the definition is made implicit is to mutualize the loop to compute several instances of phi at the same time.

Please reopen if there's something left to do.
