### ISSUE TITLE
ZeroMorph: Implement `U_n` function 

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#22]
Section 2.5 from ZeroMorph [paper](https://eprint.iacr.org/2023/917.pdf) describes function `U_n` which is responsible for mapping multilinear polynomials into univariate polynomials. Shortly, given the input multilinear polynomial coefficients, we need to evaluate it over each integer in the range [0, 2ˆn). These evaluations will become the coefficients of the output polynomial. Note this map is a homomorphism, which can be properly tested in the implementation.

**Comment by huitseeker** [comment]
This isn't singled out in https://github.com/lurk-lab/arecibo/tree/zeromorph (that is, the mapping exists, but inline in the def. of the opening's f).
I'm not opposed to the idea of making it its own function & testing the homomorphism. Please transfer to arecibo repo if you think it's still relevant.
