### ISSUE TITLE
ZeroMorph: Compute quotient polynomials `q_k`

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#23]
Section 2.5 from ZeroMorph [paper](https://eprint.iacr.org/2023/917.pdf) defines polynomials `q_k` for k > 0, such that if `f(u_0, ..., u_{k-1}) = v`, then we have that `f - v = \sum{X_k - u_k}.q_k`. 

Therefore the goal of this task is to construct all `q_k`, given as input the function `f`, the vector `u_0, ..., u_k`, and the value `v`.

**Comment by huitseeker** [comment]
In https://github.com/lurk-lab/arecibo/tree/zeromorph, test_quo passes after https://github.com/lurk-lab/arecibo/commit/2fbd2e20838273619264b88e8e3e8269c4011464 (note the nuance is in the MLE evaluation definition). Please reopen if there's anything left.
