### ISSUE TITLE
Add powers of tau in G2 for ZeroMorph scheme

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#24]
In KZG scheme we don't need powers of tau in G2. Since the skeleton implementation of ZeroMorph has a setup identical to the KZG, it is necessary to add the missing parts. 

The formal definition can be found in the description of SETUP algorithm in Page 34 from ZeroMorph [paper](https://eprint.iacr.org/2023/917.pdf).

**Comment by huitseeker** [comment]
In https://github.com/lurk-lab/arecibo/compare/dev...zeromorph
This is done in https://github.com/lurk-lab/arecibo/commit/8fea1ef4570300ec3aed0161088c5ca82bf0d50e#diff-b0f8133d0e890ded9eae607daf2fd1ee6f36bfb6b7f738540358f7a0f2d435a9
Please reopen if there's anything left
