### ISSUE TITLE
ZeroMorph: Implement polynomial evaluation subprotocol

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#25]
Implement Prove/Verify for evaluation of multilinear polynomials using ZeroMorph protocol, as described in Page 34 of ZeroMorph [paper](https://eprint.iacr.org/2023/917.pdf).

This task depends on issues #21, #22, #23, #24.

**Comment by huitseeker** [comment]
I think this is achieved in https://github.com/lurk-lab/arecibo/tree/zeromorph, but I'll leave this open pending your review.
