### ISSUE TITLE
ZeroMorph: Implement more efficient non-hiding KZG

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#26]
@huitseeker provided nice links to help us in next steps. For instance, an eprint [paper](https://eprint.iacr.org/2023/033) describing better algorithms for some auxiliar functions; a nice introduction [post](https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html); and an [implementation](https://github.com/EspressoSystems/jellyfish/tree/main/primitives/src/pcs). Notice this implementation happens over BLS12-381, then it must be adapted for BN254, meaning no FFT is available, therefore no batch algorithms. 

In this task we need to include an implementation of this version of KZG which requires just 2 pairings for verification, such that it can be used as a building block for ZeroMorph scheme.

**Comment by huitseeker** [comment]
This is done in dd0f898b6e710d2f40417e5c75c27f7b5d279ecb (part of https://github.com/lurk-lab/arecibo/tree/zeromorph), please reopen if there's something left
