### ISSUE TITLE
ZeroMorph: design and implement Polynomial interfaces

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#27]
Currently our polynomials are just arrays of elements, both for coefficient and evaluation representation. We should have a better way to represent our Polynomials, with proper structs, traits, etc. 

We need to consider the possibility of having dense and sparse polynomials.

**Comment by huitseeker** [comment]
This is done in Nova, see the extensions in https://github.com/lurk-lab/arecibo/tree/zeromorph. Please reopen if there's something left.
