### ISSUE TITLE
Make the usage of pairings generic in ZeroMorph implementation 

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/Nova#31]
For now we are just using Grumpkin, but we should make our implementation generic to work over any elliptic curve that provides an appropriate bilinear pairing.

**Comment by huitseeker** [comment]
Helped by #28, but #30 is needed to convert the current hiding variant to a generic form.

**Comment by huitseeker** [comment]
This is done in https://github.com/lurk-lab/arecibo/tree/zeromorph, please reopen if there's anything left
